In [1]:
import numpy as np

In [2]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f"Years of work: {X1}")
print(f"Earnings: {Y}")
print(f"Number of trials: {m}")


Years of work: [1 2 3 4 5 6]
Earnings: [3000 3250 3500 3750 4000 4250]
Number of trials: 6


In [13]:
X1 = X1.reshape(m, 1)
X1.shape

(6, 1)

In [15]:
bias = np.ones((m,1))
print(bias)
bias.shape

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


(6, 1)

In [17]:
X = np.append(bias, X1, axis=1)
print(X)
X.shape

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


(6, 2)

In [18]:
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [19]:
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [20]:
P = np.dot(X.T, Y)
P

array([21750., 80500.])

In [25]:
model_parameters = np.dot(L, P)

b = model_parameters[0] 
w1 = model_parameters[1] 

print("\n-------------------------")
print("Linear function:")
print(f"y = {w1:.2f}x + {b:.2f}")
print("-------------------------")


-------------------------
Linear function:
y = 250.00x + 2750.00
-------------------------


In [26]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0
